application: chris-gallery
version: 4
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: photography.py
